from __future__ import absolute_import, print_function

POSTGRES_MAX_INT = 2147483647

# class statuses
STATUS_OPEN = 0
STATUS_FULL = 1
STATUS_CLOSED = 2
STATUS_TENTATIVE = 3
STATUS_CANCELLED = 4
STATUS_STOPPED = 5

# semesters
SUMMER_TERM = 0
TRIMESTER_1 = 1
TRIMESTER_2 = 2
TRIMESTER_3 = 3


CURRENT_TERM = TRIMESTER_1

# contact types
CONTACT_TYPE_EMAIL = 0
CONTACT_TYPE_SMS = 1
CONTACT_TYPE_YO = 2

MAX_SEARCH_RESULTS = 5
